### ISSUE TITLE
Incorrect volume in mongodb service in docker-compose.template.yml

### ISSUE THREAD

**Issue by BackedUpBooty** [miroslavpejic85/mirotalkwebrtc#1]
Currently you've got the following in mongodb:

```
    volumes:
      - './.mongodb_data:/data/db'
```
however as you're creating a named volume later in the compose file it should be as follows:

```
    volumes:
      - mongodb_data:/data/db
```

**Comment by miroslavpejic85** [comment]
Hey @BackedUpBooty, 
it's like a `hidden folder`, still working anyway.

**Comment by BackedUpBooty** [comment]
Not really. When docker creates a volume, it's put into the `/var/lib/docker/volumes` directory, or some variant (dependent on the system you have it on). The way you've set up `volumes` means docker will look for a file called `.mongodb_data` inside the same directory that the compose file lives in. Those aren't always going to be the same.

**Comment by miroslavpejic85** [comment]
> The way you've set up volumes means docker will look for a file called .mongodb_data inside the same directory that the compose file lives in. 

Yeah, it is intentionally so for my use case.

> Those aren't always going to be the same.

I agree, but being now a `template` file, which is copied and edited at will, it shouldn't be a problem, as everyone can adjust it to their needs.

Thank you!
