### ISSUE TITLE
Feature Request: Disable email verification 

### ISSUE THREAD

**Issue by mms-gianni** [miroslavpejic85/mirotalkwebrtc#2]
Hey 

I try to run mirotalk on a kubernetes cluster. My problem is I don't have a mail server to rely on for the verification mails. 

An ENV var to switch this feature off would be very helpful.

**Comment by miroslavpejic85** [comment]
Hello @mms-gianni, done!

> An ENV var to switch this feature off would be very helpful.

```bash
EMAIL_VERIFICATION=true # or false (default-true)
```

**Comment by mms-gianni** [comment]
Tested: Works perfectly. Thank you. 

I just stumbled over your project today by accident. And I love it! Installed it with Kubero on my Kubernetes cluster. 

I also added it to the Kubero Template list. https://www.kubero.dev/templates

**Comment by miroslavpejic85** [comment]
> Tested: Works perfectly. Thank you.

Very good!

Thank to you for the feedback and for added [MiroTalk P2P](https://github.com/miroslavpejic85/mirotalk) on Kubero Template list! 

PS: The link in the [commit](https://github.com/kubero-dev/kubero/commit/5b3ce8203e3e2df969270a8261c0d2aeeeca69a4) seems ok, but when I click on it on Kubero, it open [another one](https://www.kubero.dev/p2p.mirotalk.com) and got `Page Not Found`. 
`Jobs Analyse (javascript)` seems not will started on your commit and the wrong URL is left.

<img width="1102" alt="kubero-wrong-url" src="https://user-images.githubusercontent.com/70838434/227147436-ad18eeee-7dc2-40a0-b47f-8784168fa051.png">

If you like join us on [discord](https://discord.gg/rgGYfeYW3N), so we can talk about, as we're going off topic of the initial task :)

Thank you!

**Comment by mms-gianni** [comment]
Fixed it.
