### ISSUE TITLE
UI Design enchancement

### ISSUE THREAD

**Issue by Villain45** [miroslavpejic85/mirotalkwebrtc#6]
Can I enhance the UI of the Login and Register Page of the website under hacktoberfest?

**Comment by miroslavpejic85** [comment]
Hello @Villain45,
Absolutely! 😊 You can absolutely enhance the UI of the Login and Register pages of a website as part of Hacktoberfest! It's a fantastic way to contribute your design skills to open-source projects and make the web a more user-friendly place. Have fun, get creative, and don't hesitate to ask for help or guidance if you need it. If we like your PR, we will gladly accept it. Happy coding! 🚀✨

**Comment by miroslavpejic85** [comment]
If necessary we will reopen it in the future, we have a dedicated channel for ideas and suggestions where you can join in our [official forum](https://discord.gg/rgGYfeYW3N) Thank you!
